apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../../docker-compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: migration-runner
  name: migration-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: migration-runner
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../../docker-compose.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: migration-runner
    spec:
      containers:
        - args:
            - bash
            - -c
            - cargo install diesel_cli --no-default-features --features postgres && cargo install just && just migrate
          env:
            - name: DATABASE_URL
              value: postgresql://db_user:db_pass@pg:5432/hyperswitch_db
          image: rust:latest
          name: migration-runner
          volumeMounts:
            - mountPath: /app
              name: migration-runner-cm0
          workingDir: /app
      restartPolicy: Always
      volumes:
        - configMap:
            name: migration-runner-cm0
          name: migration-runner-cm0
