apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../../docker-compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: pg
  name: pg
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pg
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../../docker-compose.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: pg
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: hyperswitch_db
            - name: POSTGRES_PASSWORD
              value: db_pass
            - name: POSTGRES_USER
              value: db_user
          image: postgres:latest
          livenessProbe:
            exec:
              command:
                - pg_isready
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
          name: pg
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /VAR/LIB/POSTGRESQL/DATA
              name: pg-data
      restartPolicy: Always
      volumes:
        - name: pg-data
          persistentVolumeClaim:
            claimName: pg-data
