apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../../docker-compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: redis-standalone
  name: redis-standalone
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis-standalone
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../../docker-compose.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: redis-standalone
    spec:
      containers:
        - image: redis:7
          livenessProbe:
            exec:
              command:
                - redis-cli ping | grep '^PONG$'
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
          name: redis-standalone
          ports:
            - containerPort: 6379
              protocol: TCP
      restartPolicy: Always
