[package]
name = "external_services"
description = "Interactions of the router with external systems"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
readme = "README.md"
license.workspace = true

[features]
aws_kms = ["dep:aws-config", "dep:aws-sdk-kms"]
email = ["dep:aws-config"]
aws_s3 = ["dep:aws-config", "dep:aws-sdk-s3"]
hashicorp-vault = ["dep:vaultrs"]

[dependencies]
async-trait = "0.1.79"
aws-config = { version = "1.2.0", optional = true, features = ["behavior-version-latest"] }
aws-sdk-kms = { version = "1.21.0", optional = true }
aws-sdk-sesv2 = "1.21.0"
aws-sdk-sts = "1.20.0"
aws-sdk-s3 = { version = "1.23.0", optional = true }
aws-smithy-runtime = "1.3.0"
base64 = "0.22.0"
dyn-clone = "1.0.17"
error-stack = "0.4.1"
once_cell = "1.19.0"
serde = { version = "1.0.197", features = ["derive"] }
thiserror = "1.0.58"
tokio = "1.37.0"
hyper-proxy = "0.9.1"
hyper = "0.14.28"
vaultrs = { version = "0.7.2", optional = true }
hex = "0.4.3"

# First party crates
common_utils = { version = "0.1.0", path = "../common_utils" }
hyperswitch_interfaces = { version = "0.1.0", path = "../hyperswitch_interfaces" }
masking = { version = "0.1.0", path = "../masking" }
router_env = { version = "0.1.0", path = "../router_env", features = ["log_extra_implicit_fields", "log_custom_entries_to_extra"] }
